# Generated by Django 5.0.7 on 2024-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rate',
            field=models.CharField(max_length=100, verbose_name='آدرس'),
        ),
    ]
