# Generated by Django 5.0.7 on 2024-07-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_type_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='rate',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='house',
            name='type_house',
            field=models.CharField(choices=[('S', 'فروش'), ('R', 'اجاره')], default='S', max_length=10, verbose_name=' :نوع فروش '),
        ),
    ]
