# Generated by Django 5.0.7 on 2024-08-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_rename_rate_house_address_alter_house_type_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='type_house',
        ),
    ]
