# Generated by Django 5.0.7 on 2024-08-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_remove_house_type_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('sluf', models.SlugField(verbose_name='عنوان لاتین')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار ')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='Property_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='House', to='house.property_type', verbose_name='دسته بندی'),
        ),
    ]
