# Generated by Django 5.0.7 on 2024-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_property_type_house_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='photo',
            new_name='first_photo',
        ),
        migrations.AddField(
            model_name='house',
            name='aria',
            field=models.IntegerField(default=0, verbose_name='مساحت به متر مربع'),
        ),
        migrations.AddField(
            model_name='house',
            name='bathroom',
            field=models.IntegerField(default=0, verbose_name='تعداد حمام و دسشویی'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_park',
            field=models.CharField(choices=[('sell', ' برای فروش'), ('rent', ' برای  اجاره')], default='no', max_length=10, verbose_name=' : وضعیت پارکینگ '),
        ),
        migrations.AddField(
            model_name='house',
            name='house_statue',
            field=models.CharField(choices=[('sell', ' برای فروش'), ('rent', ' برای  اجاره')], default='sell', max_length=10, verbose_name=' : وضعیت فروش '),
        ),
        migrations.AddField(
            model_name='house',
            name='room',
            field=models.IntegerField(default=0, verbose_name='تعداد خواب'),
        ),
        migrations.AddField(
            model_name='house',
            name='second_photo',
            field=models.ImageField(null=True, upload_to='house/'),
        ),
        migrations.AddField(
            model_name='house',
            name='third_photo',
            field=models.ImageField(null=True, upload_to='house/'),
        ),
    ]
