# Generated by Django 5.0.7 on 2024-08-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_alter_house_house_park_alter_house_second_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_statue',
            field=models.CharField(choices=[('برای فروش', 'برای فروش'), ('برای اجاره', 'برای اجاره')], default='برای فروش ', max_length=10, verbose_name=' : وضعیت فروش '),
        ),
    ]
