# Generated by Django 5.0.7 on 2024-08-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_alter_house_house_statue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_park',
            field=models.CharField(choices=[('دارد', ' دارد '), ('ندارد', ' ندارد  ')], default='ندارد', max_length=10, verbose_name=' : وضعیت پارکینگ '),
        ),
    ]
