# Generated by Django 5.0.7 on 2024-08-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_remove_agent_house'),
        ('house', '0011_alter_house_first_photo_alter_house_second_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Agent', to='agent.agent', verbose_name=' مشاوره املاک'),
        ),
    ]
