# Generated by Django 5.0.7 on 2024-08-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_house_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل ')),
                ('message', models.TextField(verbose_name='متن ')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
            ],
        ),
    ]
