# Generated by Django 5.0.7 on 2024-08-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0017_alter_contactagent_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactagent',
            name='agent',
        ),
    ]
