# Generated by Django 5.0.7 on 2024-08-28 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0019_contactagent_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactagent',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='house.house', verbose_name='خانه'),
        ),
    ]
