# Generated by Django 5.0.7 on 2024-08-28 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_agent_telegram'),
        ('house', '0020_alter_contactagent_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Agent', to='agent.agent', verbose_name=' مشاوره املاک'),
        ),
    ]
