# Generated by Django 5.0.7 on 2024-09-01 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0023_house_mortgage_house_rent_price_alter_house_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactagent',
            options={'managed': True, 'verbose_name': ' تماس با مشاور ملک ', 'verbose_name_plural': '  تماس ها با مشاورین ملک ها   '},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'managed': True, 'verbose_name': ' خانه ', 'verbose_name_plural': '  خانه ها   '},
        ),
        migrations.AlterModelOptions(
            name='property_type',
            options={'managed': True, 'verbose_name': ' نوع خانه ', 'verbose_name_plural': '  نوع خانه  ها   '},
        ),
        migrations.AlterField(
            model_name='contactagent',
            name='house',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='house.house', verbose_name='خانه'),
        ),
    ]
