# Generated by Django 5.0.7 on 2024-09-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': True, 'verbose_name': ' بلاگ', 'verbose_name_plural': 'بلاگ ها  '},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': ' دسته بندی', 'verbose_name_plural': ' دسته بندی ها  '},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': True, 'verbose_name': ' کامنت ', 'verbose_name_plural': '  کامنت ها   '},
        ),
    ]
