# Generated by Django 5.0.7 on 2024-09-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True, 'verbose_name': ' ارتباط   ', 'verbose_name_plural': '  ارتباط ها   '},
        ),
    ]
