# Generated by Django 5.0.7 on 2024-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(null=True, upload_to='agent/', verbose_name='تصویر'),
        ),
    ]
