# Generated by Django 5.0.7 on 2024-08-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_agent_phone_number'),
        ('house', '0011_alter_house_first_photo_alter_house_second_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='house.house', verbose_name='ملک'),
        ),
    ]
