# Generated by Django 5.0.7 on 2024-08-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agent_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='house',
        ),
    ]
