# Generated by Django 5.0.7 on 2024-08-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_remove_agent_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='telegram',
            field=models.CharField(max_length=25, null=True, verbose_name='آیدی تلگرام '),
        ),
    ]
