# Generated by Django 5.0.7 on 2024-09-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_agent_telegram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'managed': True, 'verbose_name': 'مشاور ملک', 'verbose_name_plural': 'مشاوران ملک'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='adress',
            field=models.CharField(max_length=200, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
